Key translation
SpiNNakerManchester/sPyNNaker pull request #1138
Opened 2021-12-01 12:50 UTC by rowleya

Update to make use of Key Translation from SpiNNakerManchester/SpiNNFrontEndCommon#901 and add an example.

2021-12-01 14:29 UTC, andrewgait requested changes
Looks fine to me, though as it's adding a new test I'd suggest running an integration test branch as well just to be safe.

2021-12-02 08:19 UTC, rowleya commented
You were right to request this - the test is indeed failing although I am struggling to work out why since it works for me... Further investigation is in progress

2021-12-06 07:51 UTC, rowleya commented
Tested by http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/key_translation/3/pipeline

2021-12-06 10:07 UTC, andrewgait approved these changes

2021-12-06 10:08 UTC, merged