Nuke common
SpiNNakerManchester/sPyNNaker pull request #872
Opened 2020-09-01 05:55 UTC by Christian-B

remved the relay to common object

Should not include any code change

2020-09-07 12:48 UTC, rowleya requested changes
Looks OK if this is the way you want to go; note some abstract declarations are required if you want this to be checked by Python.

2020-09-07 14:02 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
>               type(synapse_dynamics.elimination)))
these are all abstractproteries from abstract_synaspe_dynamics_structural

2020-09-07 14:03 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
>               type(synapse_dynamics.elimination)))
which this case inherits from

2020-09-07 14:04 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +        name += self.elimination.vertex_executable_suffix
same. as below comment. they defined as abstractProperties in abstract_synaspe_dynamics_structural which this class inherits from.

2020-09-07 14:06 UTC, rowleya commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +        name += self.elimination.vertex_executable_suffix
Ah I missed that change.  OK then looks fine.

2020-09-07 14:06 UTC, rowleya commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
>               type(synapse_dynamics.elimination)))
Yep, as above.

2020-09-07 14:31 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +    @abstractmethod
id concur. get_seeds should be moved to the common code. Id also argue the mask and number 4 become named  constants. and i propose RANDOM_NUMBER = 4

2020-09-07 14:33 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +    @abstractmethod
id even go further, and make those named constants part of spynnaker constants.py, as then we can use them on the constants inside SSP which also need to be named accordingly in a later pr (or feature creeped into this one).

2020-09-07 14:38 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +    @abstractmethod
furthermore. if you look at the SSP random seed settings. 
  self.__kiss_seed[vertex_slice] = validate_mars_kiss_64_seed([
                self.__rng.randint(-0x80000000, 0x7FFFFFFF) + 0x80000000
                for _ in range(4)])

the code here does not validate if the seed numbers are in the correct range, as the SSP's do. so id propose that the code in SSP should be baught into a utilitiy function that both SSP and Structural and whomever else needs it to use and have 1 place for creasting mars_kiss_64 random seeds

2020-09-10 10:56 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +    @abstractmethod
actually. cannot be done. for double inheritance issues and slots.

2020-09-10 11:17 UTC, rowleya commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +    @abstractmethod
Ah yes because of the seeds... Inheritance and slots issues is probably why I had a delegation in the first place...

2020-09-10 12:11 UTC, alan-stokes commented
so been looking to solve that diamond slot issue for SynapseDynamicsStructuralCommon and corresponding inheritance trees. 
the current and issue is shown in the slide set below:
https://docs.google.com/presentation/d/14NssN5AY2MADaefto2ZP4pZw1Ge-Ix4dQw_SpwGGB-M/edit?usp=sharing

i have not been able to find a way to detangle this without major compromises in other areas. so given that, what @Christian-B has done i think is the best we're going to get.

2020-09-10 12:13 UTC, alan-stokes commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +    @abstractmethod
so i propose, unless someone can see a way to detangle the trees in the google doc, i propose when this goes green and said tests go green, its merged into master

2020-09-10 12:20 UTC, merged