Parameters sdram usage in bytes
SpiNNakerManchester/sPyNNaker pull request #876
Opened 2020-09-03 10:31 UTC by Christian-B

Replaces https://github.com/SpiNNakerManchester/sPyNNaker/pull/870 as helpful info from @pabogdan showed that was incorrect as it did not support multiple edges.

The DSG is now done at the Machine Level so is more acturate at better if new paritioining is used.

There is still other places at the App level but that is for future work.

Tested by:

2020-09-07 13:41 UTC, alan-stokes requested changes

2020-09-07 13:42 UTC, alan-stokes commented
this ended up opening a can of worms in the skype chat when i asked what actually can be supported. this means i think this needs a bit of thinking to be as clear as possible. coz obviously it confuzzles us a lot. the fact that synapse dynamics setting causes a merge in pynn projection common AND this check makes it very confusing.

2020-09-07 14:26 UTC, rowleya commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +    PAIR_ERROR = (
The error is correct.  You can only have one structural connection between each pair of Populations.  There can only be one structural type at the target, but that is checked elsewhere.

2020-09-14 06:11 UTC, Christian-B commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +                            if (structural_edges[machine_edge] !=
YES!

2020-09-14 15:24 UTC, Christian-B commented on spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
> +                            if (structural_edges[machine_edge] !=
fixed

2020-10-08 09:22 UTC, merged